name: "Build and run unit tests"
description: "Builds and run unit tests for a .net project"

inputs:
  dotnet_version:
    description: "Version of dotnet to use for testing"
    required: true
  project_path:
    description: "Path to project to build e.g. BuildingBlocks/EventBus"
    required: true
  tests_path:
    description: "Path to test project e.g. BuildingBlocks/EventBus.Test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build and run unit tests
      shell: bash
      run: |
        cd src
        cd ${{ inputs.project_path }}
        dotnet restore
        dotnet build --no-restore
        cd -
        cd ${{ inputs.tests_path }}
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build -v=normal
