version: "3.9"  # optional since v1.27.0
services:
  auth:
    image: miau-back-auth:1.0
    container_name: miau-back-auth-container
    ports:
      - "5000:80"
    depends_on: 
      - auth_sqlserver
    restart: always

  auth_sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=Qwe123!@#
      - ACCEPT_EULA=Y
    container_name: miau-back-auth-sqlserver
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    #volumes:
    #- sqlserver_auth_data:/usr/src/miau/auth/
    restart: always
    tty: true

#volumes: # named volumes can be managed easier using docker-compose
#  sqlserver_auth_data: