name: Add issues on creating to project database-monitoring

on:
  pull_request_target:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2.0.1
        with:
          project-name: DatabaseMonitoring
          column-name: Backlog
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.PERSONAL_TOKEN }}
