name: .net notification

on:
  push:
    branches: ["main"]

    paths:
      - src/Services/Notification/**

  pull_request:
    branches: ["main"]

    paths:
      - src/Services/Notification/**

jobs:
  BuildProjectForLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-test
        with:
          dotnet_version: 7.0.x
          project_path: Services/Notification
          tests_path: Services/Notification/Notification.Tests
